import '../models/chart_case.dart';
import 'chart_recipe.dart';

class ChartRecipeCatalog {
  static List<ChartRecipe> basic() {
    return const [
      ChartRecipe(
        index: 0,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'score',
      ),
      ChartRecipe(
        index: 1,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'popularity',
        grouped: true,
      ),
      ChartRecipe(
        index: 2,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'chapters',
        grouped: true,
      ),
      ChartRecipe(
        index: 3,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'volumes',
        stacked: true,
      ),
      ChartRecipe(
        index: 4,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'score',
      ),
      ChartRecipe(
        index: 5,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'score',
        curved: true,
      ),
      ChartRecipe(
        index: 6,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'popularity',
        filled: true,
      ),
      ChartRecipe(
        index: 7,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'chapters',
        curved: true,
        filled: true,
      ),
      ChartRecipe(
        index: 8,
        level: ChartLevel.basic,
        type: 'pie',
        metricA: 'genres',
      ),
      ChartRecipe(
        index: 9,
        level: ChartLevel.basic,
        type: 'pie',
        metricA: 'types',
      ),
      ChartRecipe(
        index: 10,
        level: ChartLevel.basic,
        type: 'pie',
        metricA: 'statuses',
      ),
      ChartRecipe(
        index: 11,
        level: ChartLevel.basic,
        type: 'scatter',
        metricA: 'score',
        metricB: 'popularity',
      ),
      ChartRecipe(
        index: 12,
        level: ChartLevel.basic,
        type: 'scatter',
        metricA: 'score',
        metricB: 'chapters',
      ),
      ChartRecipe(
        index: 13,
        level: ChartLevel.basic,
        type: 'scatter',
        metricA: 'popularity',
        metricB: 'chapters',
      ),
      ChartRecipe(
        index: 14,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'ranking',
      ),
      ChartRecipe(
        index: 15,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'ranking',
        curved: true,
      ),
      ChartRecipe(
        index: 16,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'score',
        grouped: true,
      ),
      ChartRecipe(
        index: 17,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'chapters',
        stacked: true,
      ),
      ChartRecipe(
        index: 18,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'volumes',
        grouped: true,
      ),
      ChartRecipe(
        index: 19,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'volumes',
      ),
      ChartRecipe(
        index: 20,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'volumes',
        curved: true,
      ),
      ChartRecipe(
        index: 21,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'score',
        filled: true,
      ),
      ChartRecipe(
        index: 22,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'popularity',
        stacked: true,
      ),
      ChartRecipe(
        index: 23,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'popularity',
        curved: true,
      ),
      ChartRecipe(
        index: 24,
        level: ChartLevel.basic,
        type: 'scatter',
        metricA: 'score',
        metricB: 'volumes',
      ),
      ChartRecipe(
        index: 25,
        level: ChartLevel.basic,
        type: 'scatter',
        metricA: 'chapters',
        metricB: 'volumes',
      ),
      ChartRecipe(
        index: 26,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'ranking',
        grouped: true,
      ),
      ChartRecipe(
        index: 27,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'ranking',
        filled: true,
      ),
      ChartRecipe(
        index: 28,
        level: ChartLevel.basic,
        type: 'pie',
        metricA: 'authors',
      ),
      ChartRecipe(
        index: 29,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'genres',
      ),
      ChartRecipe(
        index: 30,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'types',
      ),
      ChartRecipe(
        index: 31,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'statuses',
      ),
      ChartRecipe(
        index: 32,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'score',
        filled: true,
      ),
      ChartRecipe(
        index: 33,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'chapters',
        curved: true,
      ),
      ChartRecipe(
        index: 34,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'volumes',
        filled: true,
      ),
      ChartRecipe(
        index: 35,
        level: ChartLevel.basic,
        type: 'scatter',
        metricA: 'score',
        metricB: 'popularity',
        interactive: true,
      ),
      ChartRecipe(
        index: 36,
        level: ChartLevel.basic,
        type: 'scatter',
        metricA: 'score',
        metricB: 'chapters',
        interactive: true,
      ),
      ChartRecipe(
        index: 37,
        level: ChartLevel.basic,
        type: 'scatter',
        metricA: 'popularity',
        metricB: 'chapters',
        interactive: true,
      ),
      ChartRecipe(
        index: 38,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'score',
        interactive: true,
      ),
      ChartRecipe(
        index: 39,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'score',
        interactive: true,
      ),
      ChartRecipe(
        index: 40,
        level: ChartLevel.basic,
        type: 'pie',
        metricA: 'genres',
        interactive: true,
      ),
      ChartRecipe(
        index: 41,
        level: ChartLevel.basic,
        type: 'pie',
        metricA: 'types',
        interactive: true,
      ),
      ChartRecipe(
        index: 42,
        level: ChartLevel.basic,
        type: 'pie',
        metricA: 'statuses',
        interactive: true,
      ),
      ChartRecipe(
        index: 43,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'chapters',
        interactive: true,
      ),
      ChartRecipe(
        index: 44,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'volumes',
        interactive: true,
      ),
      ChartRecipe(
        index: 45,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'popularity',
        interactive: true,
      ),
      ChartRecipe(
        index: 46,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'chapters',
        interactive: true,
      ),
      ChartRecipe(
        index: 47,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'volumes',
        interactive: true,
      ),
      ChartRecipe(
        index: 48,
        level: ChartLevel.basic,
        type: 'bar',
        metricA: 'ranking',
        interactive: true,
      ),
      ChartRecipe(
        index: 49,
        level: ChartLevel.basic,
        type: 'line',
        metricA: 'ranking',
        interactive: true,
      ),
    ];
  }

  static List<ChartRecipe> advanced() {
    return const [
      ChartRecipe(
        index: 0,
        level: ChartLevel.advanced,
        type: 'multi_line',
        metricA: 'score',
        metricB: 'popularity',
      ),
      ChartRecipe(
        index: 1,
        level: ChartLevel.advanced,
        type: 'multi_line',
        metricA: 'chapters',
        metricB: 'volumes',
      ),
      ChartRecipe(
        index: 2,
        level: ChartLevel.advanced,
        type: 'grouped_bar',
        metricA: 'score',
        metricB: 'popularity',
        metricC: 'chapters',
        grouped: true,
      ),
      ChartRecipe(
        index: 3,
        level: ChartLevel.advanced,
        type: 'stacked_bar',
        metricA: 'score',
        metricB: 'chapters',
        stacked: true,
      ),
      ChartRecipe(
        index: 4,
        level: ChartLevel.advanced,
        type: 'stacked_bar',
        metricA: 'chapters',
        metricB: 'volumes',
        stacked: true,
      ),
      ChartRecipe(
        index: 5,
        level: ChartLevel.advanced,
        type: 'scatter_line',
        metricA: 'score',
        metricB: 'popularity',
      ),
      ChartRecipe(
        index: 6,
        level: ChartLevel.advanced,
        type: 'scatter_line',
        metricA: 'score',
        metricB: 'chapters',
      ),
      ChartRecipe(
        index: 7,
        level: ChartLevel.advanced,
        type: 'scatter_line',
        metricA: 'popularity',
        metricB: 'chapters',
      ),
      ChartRecipe(
        index: 8,
        level: ChartLevel.advanced,
        type: 'year_score',
        metricA: 'score',
      ),
      ChartRecipe(
        index: 9,
        level: ChartLevel.advanced,
        type: 'year_popularity',
        metricA: 'popularity',
      ),
      ChartRecipe(
        index: 10,
        level: ChartLevel.advanced,
        type: 'year_chapters',
        metricA: 'chapters',
      ),
      ChartRecipe(
        index: 11,
        level: ChartLevel.advanced,
        type: 'year_volumes',
        metricA: 'volumes',
      ),
      ChartRecipe(
        index: 12,
        level: ChartLevel.advanced,
        type: 'genre_score',
        metricA: 'genres',
        metricB: 'score',
      ),
      ChartRecipe(
        index: 13,
        level: ChartLevel.advanced,
        type: 'genre_popularity',
        metricA: 'genres',
        metricB: 'popularity',
      ),
      ChartRecipe(
        index: 14,
        level: ChartLevel.advanced,
        type: 'type_score',
        metricA: 'types',
        metricB: 'score',
      ),
      ChartRecipe(
        index: 15,
        level: ChartLevel.advanced,
        type: 'status_score',
        metricA: 'statuses',
        metricB: 'score',
      ),
      ChartRecipe(
        index: 16,
        level: ChartLevel.advanced,
        type: 'dashboard',
        metricA: 'score',
        metricB: 'popularity',
        metricC: 'chapters',
      ),
      ChartRecipe(
        index: 17,
        level: ChartLevel.advanced,
        type: 'dashboard',
        metricA: 'genres',
        metricB: 'types',
        metricC: 'statuses',
      ),
      ChartRecipe(
        index: 18,
        level: ChartLevel.advanced,
        type: 'dashboard',
        metricA: 'score',
        metricB: 'chapters',
        metricC: 'volumes',
      ),
      ChartRecipe(
        index: 19,
        level: ChartLevel.advanced,
        type: 'dashboard',
        metricA: 'ranking',
        metricB: 'popularity',
        metricC: 'score',
      ),
      ChartRecipe(
        index: 20,
        level: ChartLevel.advanced,
        type: 'pareto',
        metricA: 'genres',
      ),
      ChartRecipe(
        index: 21,
        level: ChartLevel.advanced,
        type: 'bubble',
        metricA: 'score',
        metricB: 'chapters',
        metricC: 'popularity',
      ),
      ChartRecipe(
        index: 22,
        level: ChartLevel.advanced,
        type: 'bubble',
        metricA: 'popularity',
        metricB: 'chapters',
        metricC: 'score',
      ),
      ChartRecipe(
        index: 23,
        level: ChartLevel.advanced,
        type: 'radar',
        metricA: 'score',
        metricB: 'popularity',
        metricC: 'chapters',
      ),
      ChartRecipe(
        index: 24,
        level: ChartLevel.advanced,
        type: 'radar',
        metricA: 'score',
        metricB: 'chapters',
        metricC: 'volumes',
      ),
      ChartRecipe(
        index: 25,
        level: ChartLevel.advanced,
        type: 'multi_line',
        metricA: 'score',
        metricB: 'popularity',
        curved: true,
      ),
      ChartRecipe(
        index: 26,
        level: ChartLevel.advanced,
        type: 'multi_line',
        metricA: 'chapters',
        metricB: 'volumes',
        filled: true,
      ),
      ChartRecipe(
        index: 27,
        level: ChartLevel.advanced,
        type: 'grouped_bar',
        metricA: 'score',
        metricB: 'chapters',
        metricC: 'volumes',
        grouped: true,
      ),
      ChartRecipe(
        index: 28,
        level: ChartLevel.advanced,
        type: 'stacked_bar',
        metricA: 'genres',
        metricB: 'types',
        stacked: true,
      ),
      ChartRecipe(
        index: 29,
        level: ChartLevel.advanced,
        type: 'stacked_bar',
        metricA: 'statuses',
        metricB: 'types',
        stacked: true,
      ),
      ChartRecipe(
        index: 30,
        level: ChartLevel.advanced,
        type: 'scatter_line',
        metricA: 'score',
        metricB: 'popularity',
        interactive: true,
      ),
      ChartRecipe(
        index: 31,
        level: ChartLevel.advanced,
        type: 'bubble',
        metricA: 'score',
        metricB: 'chapters',
        metricC: 'volumes',
        interactive: true,
      ),
      ChartRecipe(
        index: 32,
        level: ChartLevel.advanced,
        type: 'dashboard',
        metricA: 'score',
        metricB: 'popularity',
        metricC: 'chapters',
        interactive: true,
      ),
      ChartRecipe(
        index: 33,
        level: ChartLevel.advanced,
        type: 'dashboard',
        metricA: 'genres',
        metricB: 'score',
        metricC: 'year',
        interactive: true,
      ),
      ChartRecipe(
        index: 34,
        level: ChartLevel.advanced,
        type: 'dashboard',
        metricA: 'ranking',
        metricB: 'chapters',
        metricC: 'volumes',
        interactive: true,
      ),
    ];
  }
}